-- main/utils/input_manager.script

function init(self)
	msg.post(".", "acquire_input_focus")
	self.target_id = nil
	self.is_active = true
	self.is_dragging = false
	self.start_pos = vmath.vector3()
	self.max_force = 50000 -- Максимальный импульс
end

function on_input(self, action_id, action)
	if not self.target_id or not self.is_active then return end

	if action_id == hash("touch") then
		if action.pressed then
			self.start_pos = vmath.vector3(action.x, action.y, 0)
			self.is_dragging = true

		elseif action.released and self.is_dragging then
			self.is_dragging = false
			local end_pos = vmath.vector3(action.x, action.y, 0)
			local drag_vector = self.start_pos - end_pos
			local length = vmath.length(drag_vector)

			if length > 0 then
				local normalized_vector = vmath.normalize(drag_vector)

				msg.post(self.target_id, "apply_impulse", { vector = normalized_vector * 50000 })
				self.is_active = false
			end			
		elseif self.is_dragging then
			-- РИСУЕМ ЛИНИЮ ПРИЦЕЛИВАНИЯ
			local current_pos = vmath.vector3(action.x, action.y, 0)
			local target_world_pos = go.get_world_position(self.target_id)

			-- Вычисляем вектор отскока (инвертированный драг)
			local diff = self.start_pos - current_pos
			local line_end = target_world_pos + diff

			-- Рисуем линию от центра юнита в сторону будущего полета
			msg.post("@render:", "draw_line", { 
				start_point = target_world_pos, 
				end_point = line_end, 
				color = vmath.vector4(1, 1, 1, 1) 
			})
		end
		end

		
	
end


-- input_manager.script

function on_message(self, message_id, message, sender)
	if message_id == hash("set_target") then
		-- 1. Сбрасываем масштаб предыдущего юнита (если он был)
		if self.target_id then
			-- Анимируем возвращение к обычному размеру
		--	go.animate(self.target_id, "scale", go.PLAYBACK_ONCE_FORWARD, vmath.vector3(1, 1, 1), go.EASING_OUTELASTIC, 0.3)
		end

		self.target_id = message.id
		self.is_active = true

		-- 2. Подсвечиваем новый активный юнит
		-- Используем vmath.vector3(1.2, 1.2, 1) для анимации масштаба по всем осям
	--	go.animate(self.target_id, "scale", go.PLAYBACK_ONCE_FORWARD, vmath.vector3(1.2, 1.2, 1), go.EASING_OUTELASTIC, 0.5)

		print("Цель установлена: " .. self.target_id)
	end
end