-- constant.script
go.property("name", hash("none")) -- Сюда прилетит значение из фабрики

function init(self)
	if self.name ~= hash("none") then
		if self.name == hash("rage") then
			self.particle_id = "#rage"
		elseif self.name == hash("freeze") then
			self.particle_id = "#freeze"
		end
		
		if self.particle_id then
			particlefx.play(self.particle_id)
		end
	end
end

function final(self)
	if self.particle_id then
		pcall(particlefx.stop, self.particle_id)
	end
end
