-- constant.script
go.property("name", hash("none")) -- Сюда прилетит значение из фабрики

function init(self)
	if self.name ~= hash("none") then
		-- Запускаем нужные частицы
		-- Превращаем хеш обратно в строку для имени компонента или используем условия
		local particle_id
		if self.name == hash("rage")  then
			particle_id = "#" .. "rage"
		elseif self.name == hash("freeze") then
			particle_id = "#" .. "freeze"
		else
			particle_id = "#" .. "trail"
		end
		
		particlefx.play(particle_id)

	end
end